CC=gcc 
CFLAGS=-c -Wall 

all: circle semicircle ring square ellipse shapes

circle: 
	gcc -Wall -o circle circle.c

semicircle:
	gcc -Wall -o semicircle semicircle.c 

ring: 
	gcc -Wall -o ring ring.c

square:
	gcc -Wall -o square square.c

ellipse:
	gcc -Wall -o ellipse ellipse.c

shapes:
	gcc -Wall -o shapes shapes.c

clean:
	rm -rf *o circle
	rm -rf *o semicircle
	rm -rf *o ring
	rm -rf *o square
	rm -rf *o ellipse
	rm -rf *o shapes
